export { default as PTop } from './PTop';
export { default as PBottom } from './PBottom';
export { DownUp, StarToDown, UpToStar } from './lottie'
export { default as GlassesEmpty } from './GlassesEmpty'
export { default as GlassesFilled } from './GlassesFilled'
export { default as DModified } from './DModified'
export { default as CModified } from './CModified'
export { default as Instagram } from './Instagram'
export { default as Linkedin } from './Linkedin'
export { default as Mail } from './Mail'